### ISSUE TITLE
Eliminate the following logged exception

### ISSUE THREAD

**Issue by szgabsz91** [szgabsz91/morpher#21]
java.nio.file.NoSuchFileException: /tmp/hunmorph-files1453972924748858009
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[na:na]
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149) ~[na:na]
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[na:na]
	at java.base/java.nio.file.Files.readAttributes(Files.java:1842) ~[na:na]
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219) ~[na:na]
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276) ~[na:na]
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322) ~[na:na]
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2795) ~[na:na]
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2875) ~[na:na]
	at com.github.*********.morpher.languagehandlers.hunmorph.impl.HunmorphWordProcessor.close(HunmorphWordProcessor.java:248) ~[morpher-language-handler-hunmorph-1.0.0.jar:na]
	at com.github.*********.morpher.languagehandlers.hunmorph.impl.HunmorphLanguageHandler.close(HunmorphLanguageHandler.java:330) ~[morpher-language-handler-hunmorph-1.0.0.jar:na]
	at com.github.*********.morpher.engines.impl.impl.MorpherEngine.close(MorpherEngine.java:317) ~[morpher-engine-impl-1.0.0.jar:na]
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:981) ~[na:na]
	at com.github.*********.morpher.systems.impl.impl.MorpherSystem.close(MorpherSystem.java:235) ~[morpher-system-impl-1.0.0.jar:na]
	at com.github.*********.morpher.api.services.MorpherService.destroy(MorpherService.java:229) ~[main/:na]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1072) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1065) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]

**Comment by szgabsz91** [comment]
Done
